#! /bin/bash
# for my raspberry pi
# post install: to be run after initialise-linux has been run

# install x windows themes, backgrounds, icons and config for user robert
# files are stored in /mnt/debhome/xconfig - themes.tar.xz, icons.tar.xz, backgrounds.tar config.tar.xz
# the link /mnt/debhome -> to root directory
# to install themes
if test -f /mnt/debhome/xconfig/themes.tar.xz; then
	# extract to /usr/share if they do not exist
	test -d /usr/share/themes/Graphite-dark-nord || tar --xz -xf /mnt/debhome/xconfig/themes.tar.xz -C /usr/share/
fi
# extract all icons if Tela-circle-dark does not exist
if test -f /mnt/debhome/xconfig/icons.tar.xz; then
	test -d /usr/share/icons/Tela-circle-dark || tar --xz -xf /mnt/debhome/xconfig/icons.tar.xz -C /usr/share/
fi
# setup mate-session as default
update-alternatives --set x-session-manager /usr/bin/mate-session

